const ITEMS = [
  { "id": 1,  "name": "Wheat Bundle",   "cat": "Material",      "rarity": "Common",    "value": 5,  "weight": "Light",  "element": "Nature", "usable": false, "danger": "Safe"      },
  { "id": 2,  "name": "Red Ruby",       "cat": "Gem",           "rarity": "Rare",      "value": 65, "weight": "Medium", "element": "Fire",   "usable": false, "danger": "Safe"      },
  { "id": 3,  "name": "Bomb",           "cat": "Weapon",        "rarity": "Uncommon",  "value": 30, "weight": "Medium", "element": "Fire",   "usable": true,  "danger": "Dangerous" },
  { "id": 4,  "name": "Purple Diamond", "cat": "Gem",           "rarity": "Legendary", "value": 90, "weight": "Medium", "element": "Dark",   "usable": false, "danger": "Safe"      },
  { "id": 5,  "name": "Gray Rocks",     "cat": "Material",      "rarity": "Common",    "value": 3,  "weight": "Heavy",  "element": "Earth",  "usable": false, "danger": "Safe"      },
  { "id": 6,  "name": "Cactus Ball",    "cat": "Plant",         "rarity": "Uncommon",  "value": 20, "weight": "Medium", "element": "Nature", "usable": true,  "danger": "Moderate"  },
  { "id": 7,  "name": "Blue Potion",    "cat": "Consumable",    "rarity": "Rare",      "value": 45, "weight": "Light",  "element": "Water",  "usable": true,  "danger": "Safe"      },
  { "id": 8,  "name": "Aloe Plant",     "cat": "Plant",         "rarity": "Common",    "value": 12, "weight": "Light",  "element": "Nature", "usable": true,  "danger": "Safe"      },
  { "id": 9,  "name": "Gold Bar",       "cat": "Material",      "rarity": "Rare",      "value": 80, "weight": "Heavy",  "element": "None",   "usable": false, "danger": "Safe"      },
  { "id": 10, "name": "Toxic Slime",    "cat": "Creature Drop", "rarity": "Uncommon",  "value": 25, "weight": "Light",  "element": "Toxic",  "usable": true,  "danger": "Dangerous" },

  { "id": 11, "name": "Iron Sword",      "cat": "Weapon",        "rarity": "Uncommon",  "value": 35, "weight": "Medium", "element": "None",       "usable": true,  "danger": "Dangerous" },
  { "id": 12, "name": "Health Potion",   "cat": "Consumable",    "rarity": "Common",    "value": 15, "weight": "Light",  "element": "None",       "usable": true,  "danger": "Safe"      },
  { "id": 13, "name": "Ice Crystal",     "cat": "Gem",           "rarity": "Rare",      "value": 55, "weight": "Light",  "element": "Ice",        "usable": false, "danger": "Safe"      },
  { "id": 14, "name": "Wolf Fang",       "cat": "Creature Drop", "rarity": "Common",    "value": 8,  "weight": "Light",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 15, "name": "Thunder Stone",   "cat": "Material",      "rarity": "Uncommon",  "value": 28, "weight": "Medium", "element": "Lightning",  "usable": false, "danger": "Moderate"  },
  { "id": 16, "name": "Dark Dagger",     "cat": "Weapon",        "rarity": "Rare",      "value": 60, "weight": "Light",  "element": "Dark",       "usable": true,  "danger": "Dangerous" },
  { "id": 17, "name": "Mushroom Cap",    "cat": "Plant",         "rarity": "Common",    "value": 6,  "weight": "Light",  "element": "Nature",     "usable": true,  "danger": "Moderate"  },
  { "id": 18, "name": "Sapphire",        "cat": "Gem",           "rarity": "Rare",      "value": 70, "weight": "Medium", "element": "Water",      "usable": false, "danger": "Safe"      },
  { "id": 19, "name": "Steel Ingot",     "cat": "Material",      "rarity": "Uncommon",  "value": 40, "weight": "Heavy",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 20, "name": "Fire Scroll",     "cat": "Consumable",    "rarity": "Rare",      "value": 50, "weight": "Light",  "element": "Fire",       "usable": true,  "danger": "Dangerous" },
  { "id": 21, "name": "Emerald",         "cat": "Gem",           "rarity": "Rare",      "value": 65, "weight": "Medium", "element": "Nature",     "usable": false, "danger": "Safe"      },
  { "id": 22, "name": "Poison Arrow",    "cat": "Weapon",        "rarity": "Uncommon",  "value": 32, "weight": "Light",  "element": "Toxic",      "usable": true,  "danger": "Dangerous" },
  { "id": 23, "name": "Healing Herb",    "cat": "Plant",         "rarity": "Common",    "value": 10, "weight": "Light",  "element": "Nature",     "usable": true,  "danger": "Safe"      },
  { "id": 24, "name": "Mana Crystal",    "cat": "Gem",           "rarity": "Uncommon",  "value": 38, "weight": "Light",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 25, "name": "Shadow Orb",      "cat": "Consumable",    "rarity": "Legendary", "value": 95, "weight": "Light",  "element": "Dark",       "usable": true,  "danger": "Dangerous" },
  { "id": 26, "name": "Iron Ore",        "cat": "Material",      "rarity": "Common",    "value": 7,  "weight": "Heavy",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 27, "name": "Spider Silk",     "cat": "Creature Drop", "rarity": "Uncommon",  "value": 22, "weight": "Light",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 28, "name": "Lava Rock",       "cat": "Material",      "rarity": "Uncommon",  "value": 18, "weight": "Heavy",  "element": "Fire",       "usable": false, "danger": "Moderate"  },
  { "id": 29, "name": "Moonstone",       "cat": "Gem",           "rarity": "Rare",      "value": 75, "weight": "Medium", "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 30, "name": "Explosive Powder","cat": "Material",      "rarity": "Rare",      "value": 55, "weight": "Light",  "element": "Fire",       "usable": true,  "danger": "Dangerous" },
  { "id": 31, "name": "Bamboo Staff",    "cat": "Weapon",        "rarity": "Common",    "value": 14, "weight": "Medium", "element": "Nature",     "usable": true,  "danger": "Moderate"  },
  { "id": 32, "name": "Water Vial",      "cat": "Consumable",    "rarity": "Common",    "value": 9,  "weight": "Light",  "element": "Water",      "usable": true,  "danger": "Safe"      },
  { "id": 33, "name": "Dragon Scale",    "cat": "Creature Drop", "rarity": "Legendary", "value": 100,"weight": "Heavy",  "element": "Fire",       "usable": false, "danger": "Moderate"  },
  { "id": 34, "name": "Cursed Totem",    "cat": "Weapon",        "rarity": "Rare",      "value": 68, "weight": "Medium", "element": "Dark",       "usable": true,  "danger": "Dangerous" },
  { "id": 35, "name": "Pine Cone",       "cat": "Plant",         "rarity": "Common",    "value": 4,  "weight": "Light",  "element": "Nature",     "usable": false, "danger": "Safe"      },
  { "id": 36, "name": "Amethyst",        "cat": "Gem",           "rarity": "Uncommon",  "value": 42, "weight": "Light",  "element": "Dark",       "usable": false, "danger": "Safe"      },
  { "id": 37, "name": "Acid Flask",      "cat": "Consumable",    "rarity": "Uncommon",  "value": 35, "weight": "Light",  "element": "Toxic",      "usable": true,  "danger": "Dangerous" },
  { "id": 38, "name": "Coal Chunk",      "cat": "Material",      "rarity": "Common",    "value": 5,  "weight": "Heavy",  "element": "Fire",       "usable": false, "danger": "Safe"      },
  { "id": 39, "name": "Bone Fragment",   "cat": "Creature Drop", "rarity": "Common",    "value": 11, "weight": "Light",  "element": "None",       "usable": false, "danger": "Safe"      },
  { "id": 40, "name": "Lightning Rod",   "cat": "Weapon",        "rarity": "Uncommon",  "value": 30, "weight": "Medium", "element": "Lightning",  "usable": true,  "danger": "Moderate"  }
];
